dist: xenial
language: go
go:
    - master

# before_install
# install - install any dependencies required
install:
    - sudo apt-get update
    - sudo apt-get install hugo

before_script:
    - rm -rf public 2> /dev/null

# script - run the build script
script:
    - bash scripts/publish_to_ghpages.sh
