baseURL = "https://asepbagja.com/"
DefaultContentLanguage = "en"
languageCode = "en-gb"
theme = "bepitulaz" # set the theme
copyright="2019 © Asep Bagja Priandana"
googleAnalytics = "UA-136771948-2"
#googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true
disqusShortname = "asepnew"
summaryLength = 10

[languages]
  [languages.en]
    title = "Asep Bagja & Co."
    weight = 1
    contentDir = "content/en"
    languageName = "English"
    staticDir = "static/en"
    [languages.en.params]
      main = "Hi, I'm Asep :wave:"
      sub = "The Tech Consultant"
      postsTitle = "Posts"
      postsReadMore = "READ MORE"
      aboutMe = "About Asep"
    [languages.en.blackfriday]
      angledQuotes = false

  [[languages.en.menu.main]]
    url    = "/"
    name   = "Home"
    weight = 0
  [[languages.en.menu.about]]
    url    = "/about"
    name   = "About"
    weight = 1
  [[languages.en.menu.posts]]
    url    = "/posts"
    name   = "Posts"
    weight = 2

  [languages.id]
    title = "Asep Bagja & Co."
    weight = 2
    contentDir = "content/id"
    languageName = "Bahasa Indonesia"
    staticDir = "static"
    [languages.id.params]
      main = "Hai, saya Asep :wave:"
      sub = "Konsultan Teknologi"
      postsTitle = "Artikel"
      postsReadMore = "BACA LEBIH BANYAK"
      aboutMe = "Tentang Asep"

  [[languages.id.menu.main]]
    url    = "/"
    name   = "Beranda"
    weight = 0
  [[languages.id.menu.about]]
    url    = "/tentang-saya"
    name   = "Tentang Saya"
    weight = 1
  [[languages.id.menu.posts]]
    url    = "/artikel"
    name   = "Artikel"
    weight = 2
