baseURL = "https://asepbagja.com/"
languageCode = "en-gb"
title = "ASPBGJ"
theme = "hugo-coder" # set the theme
googleAnalytics = "UA-136771948-2"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "Asepnew"

[params] # theme parameters
    author = "Asep Bagja Priandana" # author's name
    info = "A Software Developer and Entrepreneur" # author's job title or info
    description = "My personal web" # site description
    keywords = "blog,developer,personal" # site keywords
    avatarurl = "images/avatar.jpg"
    hidecredits = false
    hidecopyright = false
    rtl = false
    math = true
    
# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/bepitulaz/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/bepitulaz/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/asepbagja/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium fa-2x"
    weight = 4
    url = "https://medium.com/@bepitulaz"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"

[[menu.main]]
    name = "About"
    weight = 1
    url  = "/about/"

[[menu.main]]
    name = "Shop"
    weight = 3
    url  = "/shop/"
