baseURL = "https://asepbagja.com/"
DefaultContentLanguage = "id"
languageCode = "en-gb"
theme = "Podcaster" # set the theme
copyright="2020 © Asep Bagja Priandana"
googleAnalytics = "UA-136771948-2"
#googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true
disqusShortname = "asepnew"
summaryLength = 10

rssLimit = 10

[author]
  email = "asep.bagja.p@gmail.com"
  name = "Asep Bagja Priandana"
  avatar = "/images/avatar.jpg"

[languages]
  [languages.en]
    title = "Asep Bagja & Co."
    weight = 1
    contentDir = "content/en"
    languageName = "English"
    staticDir = "static/en"
    [languages.en.params]
      main = "Hi, I'm Asep :wave:"
      sub = "The Tech Consultant"
      postsTitle = "Posts"
      postsReadMore = "READ MORE"
      aboutMe = "About Asep"
      socialShare = "Share this content"
      description = "The personal blog of Asep Bagja"
    [languages.en.blackfriday]
      angledQuotes = false

  [[languages.en.menu.article]]
    url    = "/posts"
    name   = "Posts"
    weight = 0
  [[languages.en.menu.podcast]]
    url    = "/podcast"
    name   = "Podcast"
    weight = 1
  [[languages.en.menu.about]]
    url    = "/about"
    name   = "About me"
    weight = 2

  [languages.id]
    title = "Asep Bagja & Co."
    weight = 2
    contentDir = "content/id"
    languageName = "Bahasa Indonesia"
    staticDir = "static"
    [languages.id.params]
      main = "Hai, saya Asep :wave:"
      sub = "Konsultan Teknologi"
      postsTitle = "Artikel"
      postsReadMore = "BACA LEBIH BANYAK"
      aboutMe = "Tentang Asep"
      socialShare = "Bagikan konten ini"
      description = "Blog pribadi Asep Bagja"

  [[languages.id.menu.article]]
    url    = "/artikel"
    name   = "Artikel"
    weight = 0
  [[languages.id.menu.podcast]]
    url    = "/podcast"
    name   = "Podcast"
    weight = 1
  [[languages.id.menu.about]]
    url    = "/tentang-saya"
    name   = "Tentang saya"
    weight = 2
