baseURL = "https://asepbagja.com/"
languageCode = "en-gb"
title = "ASPBGJ"
theme = "personal-web" # set the theme
copyright="2019 © Asep Bagja Priandana"
googleAnalytics = "UA-136771948-2"
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true
disqusShortname = "asepnew"

[params.intro]
  main = "Hi, I'm Asep :wave:"
  sub = "A technology entrepreneur"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['post'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '/images/sidebar.jpg' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/avatar.jpg" # - default "/images/edna-west.jpg"
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/bepitulaz"
  twitter = "https://twitter.com/bepituLaz"
  linkedin = "https://www.linkedin.com/in/asepbagja"
  instagram = "https://www.instagram.com/bepitulaz"

[params.contact]
  email = "asep.bagja.p@gmail.com"
  text= "Send me an email 📧" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "blog"
  name = "Posts"
  title = "Blog section"
  url = "/posts/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false